extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:node/recommended-script
  - plugin:promise/recommended
  - standard
parserOptions:
  ecmaVersion: 2018
rules:
  import/newline-after-import: error
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "*"
        - ".*"
        - "**/tests/**"
  import/order:
    - error
    - groups:
        - builtin
        - [external, internal]
        - [parent, sibling, index]
        - unknown
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
overrides:
  - files: "*.js"
    extends:
      - plugin:dprint/recommended
    rules:
      dprint/dprint:
        - error
        - config:
            indentWidth: 2
            quoteStyle: preferSingle
            singleBodyPosition: sameLine
            typeParameters.trailingCommas: never
            arrowFunction.useParentheses: preferNone
            constructorType.spaceAfterNewKeyword: true
            taggedTemplate.spaceBeforeLiteral: false
            typeAssertion.spaceBeforeExpression: false
