extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:node/recommended-script
  - plugin:promise/recommended
  - standard
parserOptions:
  # Node.js 12 and above almost supports features up to ES2019
  # see https://node.green/#ES2019
  ecmaVersion: 2019
settings:
  # `eslint-plugin-import@2.26.0` does not detect the `exports` field in `package.json`.
  # So change resolver to `eslint-import-resolver-enhanced-resolve`.
  # see https://github.com/import-js/eslint-plugin-import/issues/1810
  import/resolver:
    node: # This is the default resolver for `eslint-plugin-import`. If omitted, Node.js modules cannot be loaded.
    enhanced-resolve: {}
rules:
  import/newline-after-import: error
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "*"
        - ".*"
        - "**/*.test-d.ts"
        - "**/tests/**"
  import/order:
    - error
    - groups:
        - builtin
        - [external, internal]
        - [parent, sibling, index]
        - unknown
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
overrides:
  - files: "*.cjs"
  - files:
      - "*.mjs"
      - "**/rollup.config.js"
    parserOptions:
      sourceType: module
    rules:
      node/no-unsupported-features/es-syntax:
        - error
        - ignores:
            - modules
  - files: "*.ts"
    extends:
      - plugin:node/recommended-module
      - plugin:@typescript-eslint/recommended
      - plugin:import/typescript
      - standard-with-typescript
    parserOptions:
      sourceType: module
      project:
        - ./packages/{*,*/*}/src/tsconfig.json
        - ./packages/{*,*/*}/tests/helpers/tsconfig.json
        - ./packages/{*,*/*}/tests/tsconfig.json
        - ./packages/{*,*/*}/test-d/tsconfig.json
        - ./packages/{*,*/*}/tsconfig.json
          # Note: The package root tsconfig must be written after the subdirectory of tsconfig.
          #       Writing it before the subdirectory may cause erroneous errors
          #       because ESLint will use the package root tsconfig before the subdirectory tsconfig.
        - ./actions/*/src/tsconfig.json
        - ./actions/*/tests/helpers/tsconfig.json
        - ./actions/*/tests/tsconfig.json
        - ./actions/*/test-d/tsconfig.json
        - ./actions/*/tsconfig.json
    settings:
      node:
        # see https://github.com/mysticatea/eslint-plugin-node/blob/v11.1.0/docs/rules/shebang.md
        convertPath:
          src/**/*.ts:
            - ^src/(.+?)\.ts$
            - dist/$1.js
    rules:
      # The "@typescript-eslint/no-floating-promises" rule requires a void operator to be used as a statement.
      # see https://github.com/typescript-eslint/typescript-eslint/blob/v4.21.0/packages/eslint-plugin/docs/rules/no-floating-promises.md
      no-void:
        - error
        - allowAsStatement: true
      # TypeScript checks the import statement path.
      # Therefore, there is no need to verify the file path imported by ESLint.
      import/no-unresolved: off
      node/no-missing-import: off
      # The "node/no-unpublished-import" rule does not support "import type ... from '...'" statements.
      # This causes an error when importing a type definition file that is not published.
      node/no-unpublished-import: off
      # I don't want to use "nodeify" package.
      promise/no-callback-in-promise: off
      # The "@typescript-eslint/strict-boolean-expressions" rule is very strict and stressful.
      "@typescript-eslint/strict-boolean-expressions": off
  - files: "*.d.ts"
    rules:
      # The "no-redeclare" rule does not support namespace and function declarations of the same name.
      # example:
      #   declare function foo(): void;
      #   declare namespace foo { ... } // ESLint: error 'foo' is already defined
      # In addition, as of 2020/06/11, there is no alternative to the "no-redeclare" rule in "@typescript-eslint"
      no-redeclare: off
      # The "@ts-expect-error" comment is not allowed in TypeScript 3.8 or earlier.
      # If someone forks a type definition created in this project, the type definition will not be available in older versions of TypeScript.
      "@typescript-eslint/prefer-ts-expect-error": off
  - files:
      - "**/tests/*.ts"
      - "**/tests/!(helpers!(?))*{,/**}/*.ts"
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
    rules:
      jest/consistent-test-it: error
      jest/no-deprecated-functions: error
      jest/no-duplicate-hooks: error
      jest/no-if: error
      jest/no-test-return-statement: error
      jest/prefer-lowercase-title: error
      jest/prefer-spy-on: error
      jest/prefer-strict-equal: error
      jest/prefer-todo: error
      jest/require-top-level-describe: error
      jest/valid-title: error
  - files: "**/examples/**"
    rules:
      node/no-missing-require: off
  - files:
      - .lintstagedrc.js
      - scripts/*.js
      - jest.config.base.cjs
      - "**/jest.config.{js,cjs}"
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
      node/no-unpublished-require: off
      node/no-unsupported-features/es-syntax:
        - error
        - version: 12.x
      node/no-unsupported-features/node-builtins:
        - error
        - version: 12.x
  - files: "**/rollup.config.js"
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
  - files: "*"
    extends:
      - prettier
