packages:
  - packages/*
  - packages/cli/*
  - packages/cli-utils/*
  - packages/ts-utils/*
  - packages/ts-type-utils/*
  - packages/jest-matchers/*
  - actions/*
  - scripts
  - scripts/*
  - "**/examples"
  - "**/examples/*"
