name: Setup pnpm environment
author: sounisi5011
description: Install and set up pnpm, the version of pnpm will be automatically detected from the `engines` field in the `package.json` file in the project root
runs:
  using: composite
  steps:
    - name: Detect pnpm version
      id: get-pnpm-data
      shell: bash
      run: node ${{ github.action_path }}/get-pnpm-data.js
    - name: Install pnpm@${{ steps.get-pnpm-data.outputs.pnpm-version-range }}
      shell: bash
      run: npm i -g pnpm@${{ steps.get-pnpm-data.outputs.pnpm-version-range }}
