name: Find Workspace Submodules
author: sounisi5011
description: Get the path and package name of a node submodules in npm/yarn/pnpm workspaces
inputs:
  ignore-private:
    description: If you want to exclude submodules whose "private" field is set to `true`, set this option to `true`
    required: false
    default: false
  only-changed-since:
    description: |
      Returns only submodules that have changed since the specified point in time.
      The default is "initial commit". This means that all submodules will be returned.
      For other values, please refer to the documentation.
    required: false
    default: initial commit
  token:
    description: Personal access token (PAT) used to fetch data from the repository.
    required: false
    default: ${{ github.token }}
outputs:
  result:
    description: JSON string of an array that includes the path and package name pairs of each submodule
  submodule-exists:
    description: If `result` contains one or more submodules, it is `true`.
runs:
  using: node16
  main: dist/index.js
