#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Note: This file should be POSIX compliant.
#       If you edit this file, use "checkbashisms" to check it does not contain bash, zsh, or other features.

./node_modules/.bin/lint-staged
