name: CI
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - "**"
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Setup pnpm
        uses: ./actions/setup-pnpm
      - name: Install Dependencies
        run: pnpm install
      - run: pnpm run lint
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Setup pnpm
        uses: ./actions/setup-pnpm
      - name: Install Dependencies
        run: pnpm install
      - run: pnpm run fmt-check
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 12.x
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Setup pnpm
        uses: ./actions/setup-pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Build flatbuffers
        shell: bash
        # https://google.github.io/flatbuffers/flatbuffers_guide_building.html
        run: |
          readonly FLATBUFFERS_BUILD_PATH='./.flatbuffers'

          echo '::group::$' git clone --depth 1 https://github.com/google/flatbuffers.git -b v1.12.0 "${FLATBUFFERS_BUILD_PATH}"
                            git clone --depth 1 https://github.com/google/flatbuffers.git -b v1.12.0 "${FLATBUFFERS_BUILD_PATH}"
          echo '::endgroup::'

          echo '$' cd "${FLATBUFFERS_BUILD_PATH}"
                   cd "${FLATBUFFERS_BUILD_PATH}"

          echo '::group::$' cmake -G '"Unix Makefiles"'
                            cmake -G  'Unix Makefiles'
          echo '::endgroup::'

          echo '::group::$' git diff --name-only
                            git diff --name-only
          echo '::endgroup::'

          echo '::group::$' git clean -xdn
                            git clean -xdn
          echo '::endgroup::'

          echo '::group::$' ls -lpa CMakeFiles/*
                            ls -lpa CMakeFiles/*
          echo '::endgroup::'

          echo '$' cd ..
                   cd ..

          flatc --version
      - run: pnpx run-s build build-flatbuffers
      - name: Check changes
        if: ${{ always() }}
        run: git diff --exit-code
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 10.x
          - 12.x
          - 14.x
          - 15.x
    steps:
      - uses: actions/checkout@v2
      - name: Git Setting
        run: |
          git config --global user.name  CI
          git config --global user.email dummy@example.com
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Setup pnpm
        uses: ./actions/setup-pnpm
      - name: Install Dependencies
        run: pnpm install
      - run: pnpm run test-only
  complete:
    # see https://github.community/t/status-check-for-a-matrix-jobs/127354/7
    name: Complete CI
    needs: [lint, format, build, unit-test]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check all job status
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
