name: Auto Approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  approve:
    # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
    # see https://stackoverflow.com/a/67532120/4907315
    if: >-
      ${{
        github.event.pull_request.user.login == github.repository_owner
        && ! github.event.pull_request.draft
        && ! contains(github.event.pull_request.labels.*.name, 'skip ci')
      }}
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
