name: Auto Approve
on: pull_request
jobs:
  approve:
    if: ${{ github.actor == github.repository_owner || github.event.pusher.name == github.repository_owner }}
    runs-on: ubuntu-latest
    steps:
      - name: Show envs
        run: |
          echo 'github.actor' '$${{ github.actor }}'
          echo 'github.event.pusher.name' '$${{ github.event.pusher.name }}'
          echo 'github.repository_owner' '$${{ github.repository_owner }}'
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
