name: Auto Approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  approve:
    if: ${{ github.event.pull_request.user.login == github.repository_owner && ! github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Show envs
        run: |
          echo 'github.actor' '${{ github.actor }}'
          echo 'github.event.pusher.name' '${{ github.event.pusher.name }}'
          echo 'github.event.pull_request.user.login' '${{ github.event.pull_request.user.login }}'
          echo 'github.repository_owner' '${{ github.repository_owner }}'
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
