name: Release
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
jobs:
  submodules-finder:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.interrogate.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - id: interrogate
        uses: ./actions/workspace-submodules
  release-please:
    runs-on: ubuntu-latest
    needs: submodules-finder
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.submodules-finder.outputs.result)}}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: ${{ matrix.package-name }}
          path: ${{ matrix.path-git-relative }}
          monorepo-tags: true
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v2
        with:
          node-version: 12
        if: ${{ steps.release.outputs.release_created }}
      - name: Cache .pnpm-store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node-12-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-12-
            ${{ runner.os }}-node-
            ${{ runner.os }}-
        if: ${{ steps.release.outputs.release_created }}
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm i -g pnpm
          pnpm install
          cd '${{ matrix.path-git-relative }}'
          pnpm publish --access=public
        if: ${{ steps.release.outputs.release_created }}
