name: Release
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
jobs:
  submodules-finder:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.interrogate.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      - id: interrogate
        uses: ./actions/monorepo-workspace-submodules-finder
  release-please:
    runs-on: ubuntu-latest
    needs: submodules-finder
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.submodules-finder.outputs.result)}}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: ${{ matrix.package-name }}
          path: ${{ matrix.path-git-relative }}
          monorepo-tags: true
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org
          # Note: The `registry-url` option is required.
          #       If this option is not set, the "npm publish" command will not detect the environment variable NODE_AUTH_TOKEN.
        if: ${{ steps.release.outputs.release_created }}
      - uses: ./actions/setup-pnpm
        if: ${{ steps.release.outputs.release_created }}
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          readonly CUSTOM_PUBLISH_SCRIPT_PATH=.github/workflows/publish.sh
          pnpm install
          cd '${{ matrix.path-git-relative }}'
          pnpm run build --if-present
          if [ -x "${CUSTOM_PUBLISH_SCRIPT_PATH}" ]; then
            GITHUB_TOKEN='${{ secrets.GITHUB_TOKEN }}'
            matrix_package_name='${{ matrix.package-name }}'
            outputs_upload_url='${{ steps.release.outputs.upload_url }}'
            outputs_html_url='${{ steps.release.outputs.html_url }}'
            outputs_tag_name='${{ steps.release.outputs.tag_name }}'
            outputs_major='${{ steps.release.outputs.major }}'
            outputs_minor='${{ steps.release.outputs.minor }}'
            outputs_patch='${{ steps.release.outputs.patch }}'
            outputs_sha='${{ steps.release.outputs.sha }}'
            outputs_pr='${{ steps.release.outputs.pr }}'
            echo loading "${CUSTOM_PUBLISH_SCRIPT_PATH}"
            source "${CUSTOM_PUBLISH_SCRIPT_PATH}"
          else
            pnpm publish --access=public
          fi
        shell: bash
        if: ${{ steps.release.outputs.release_created }}
